### PR TITLE
Arbitrary stopwords lists

### PR DESCRIPTION
**Pull request by nOkuda**
Store custom stopwords lists in MongoDB for later retrieval; part of the API.

### CODE REVIEW

**Comment by jeffkinnison** [comment]
I don't see an issue with this, but out of curiosity are you thinking to accept stoplist words from the user through the frontend/API?

**Comment by nOkuda** [comment]
Yes.

James and Cari put together some stopwords lists full of function words.  I guess we could have made them put the lists directly into the database, but I figured it wasn't too difficult to add this to the API.

**Comment by jeffkinnison** [comment]
Just one thing: the database structure has changed pretty significantly since this PR was introduced. I think a nicer way to handle this might be to keep a list of FeatureSet references, which would give us the ability to use the stoplists with arbitrary features with no extra logic.

**Comment by nOkuda** [comment]
With the new aggregation pipeline matching, will feature sets match only when they contain exactly the same information, or so long as the intersection of feature sets is not empty?  (Also, could you point me to the place in the code where this happens?)

Should we force stopwords lists to be associated with a specific feature?

I'm thinking of the use case of a user crafting a new stopwords list.  If the user gets unexpected behavior by the way feature sets work, that could be problematic.  I can see us doing the extra logic work up front by crafting feature sets based on what the user decides to input, in the case that aggregation works by non empty intersection.  Otherwise, I foresee some very confused users.

The way I had envisioned the stopwords lists to work is as you suggested, that we do the extra logic work to look up feature sets based on which feature the user chooses to match on.  Will that be too slow?

**Comment by jeffkinnison** [comment]
The current stoplist computation functionality can be found [here](https://github.com/tesserae/tesserae-v5/blob/066c958b52543a4fe032af4dc7e205c953b742a3/tesserae/matchers/aggregator.py#L41-L107). It uses the Frequency entity, which maps the number of occurrences of a particular FeatureSet to a particular Text. I think there's some wrong reasoning here, though, with regards to how lemmata are being handled. Maybe form should be separated from FeatureSet and associated with Token, with FeatureSet applying to any form that generates the same set of features?

I don't think it's necessary to force stoplists to particular features, we can do that mapping in-database, but for bookkeeping it would probably be nice to include that information.

Maybe there's some confusion here, but we're not crafting FeatureSets on the fly during matching, those are set at tokenization.

The current stoplist creation code runs in about 2s, including the time needed to pull the information back from the database. Unless we replicate a lot of information across collections in the database, I don't know if we can make this happen more quickly.

**Comment by nOkuda** [comment]
Yes, we are talking about slightly different things, I think.  I am interested in the part of the matching code that inspects FeatureSets between tokens and determines whether there is a match between potential lemmata of the tokens.

The stopwords list should then intervene at this point, where if the tokens are considered a match solely because of lemmata found in the stopwords list, the two units should not be considered a match.

The arbitrary stopwords list should allow the user to specify what those stopwords are without having to specify all of the other features in the FeatureSet.

Is this possible given the current state of the database?  Or should we push this use case to a later version of the service?

**Comment by nOkuda** [comment]
Now that I've looked at the code a little harder and thought things through a little longer, I think I see what you are suggesting.

In storing the stopwords lists in the database, we'll just keep lists of `ObjectId`s to `FeatureSet`s.  When the user specifies via the API what stopwords to put into a new stopwords list, the API will construct the list by looking up the specified words in the `FeatureSet`s in the database.  And when the user requests a given stopwords list, the API will transform the `ObjectId`s into the proper forms.

Is this correct?

The follow up question:  what should we do when a user inputs a form that doesn't exist in the database?

**Comment by nOkuda** [comment]
Another thought:  the API allows for stopwords lists made on the fly to be submitted for match search  By this, I mean that the API is designed to accept an explicit list of strings as a stopwords list.  (In contrast, the "arbitrary stopwords list" I refer to as the title of this pull request is a pre-canned stopwords list that the database keeps around.)

I'm inclined to keep the pull request as is and work on decoupling stopwords list generation from match search in a different pull request.  That way, arbitrary stopwords lists can more easily play with the code base.

Do you think this to be a good solution?

**Comment by nOkuda** [comment]
During the group phone call, we decided that leaving this pull request as is should be fine.

**Pull request merged**
