### PR TITLE
EnglishTokenizer

### LINKED ISSUE #33: Feature.feature has "lemmata" instead of "lemma"
Just found this by printing out a Feature object with my new __repr__() method.  We can track this down after I push my code.

### PR DESCRIPTION
**Pull request by nOkuda**
Resolves #33

### CODE REVIEW

**Comment by jeffkinnison** [comment]
Are there texts you selected for the unit tests?

**Comment by nOkuda** [comment]
I don't have external files for the unit tests.  There are, however, a list of strings embedded within the test functions which imitate a line-by-line reading of an external file (see tests/tokenizers/languages/test_english.py).

**Comment by jeffkinnison** [comment]
The only thing I see is that [tesserae/tokenizers/english.py](https://github.com/nOkuda/tesserae-v5/blob/645aa9cdbd013aab773572199248cccd54e73313/tesserae/tokenizers/english.py#L13-L14 "English Tokenizer lines 13-14") should be updated from

```
        self.split_pattern = \
            r'[^\w]+'
```

to

```
        self.split_pattern = \
            r'( / )|([\s]+)|([^\w]+)'
```

This scheme lets us split on/grab both the Tesserae-style newline token and word tokens in a single string in one shot.

**Comment by jeffkinnison** [comment]
One more thing: in tesserae/tokenizers/english.py, the following two lines need to be added somewhere in the file (maybe the constructor?):

```python
import nltk
nltk.download('wordnet')
```

**Comment by nOkuda** [comment]
Finally got around to updating EnglishTokenizer.

I put the nltk wordnet downloading into setup.py using the instructions at https://www.nltk.org/data.html#manual-installation.  Did that not work?  At least on the production server, we can't easily get away with the two lines you've suggested (SELinux freaks out unless we chant some magical incantations).

**Pull request closed without merging**
