### PR TITLE
Retrieve search results

### PR DESCRIPTION
**Pull request by nOkuda**
It's slow, but it works.

I intend to make search result retrieval faster, but I wanted these changes in before I ventured on that quest.

### CODE REVIEW

**Comment by jeffkinnison** [comment]
Is this separate from the lemma frequency slowdown?

**Comment by nOkuda** [comment]
I guess I should have updated the message.

Results retrieval is now fast enough (~5 seconds on my laptop for the Lucan-Vergil search---though I haven't gotten the text snippets in there yet, so there's a little more work to do on that front).

Search slowdown is related to the fix I introduced for lemma frequency calculation (which I have included in this pull request).

**Comment by jeffkinnison** [comment]
Cool, I'll have at the scoring bit this afternoon, see if I can't speed things up.

**Comment by nOkuda** [comment]
Here are some resources I've found that seem potentially useful for the speeding up:
* https://stackoverflow.com/questions/4319014/iterating-through-a-scipy-sparse-vector-or-matrix  
* https://stackoverflow.com/questions/35773101/efficient-incremental-sparse-matrix-in-python-scipy-numpy 
* https://bergvca.github.io/2017/10/14/super-fast-string-matching.html

Here's the general algorithm I outlined (I was thinking of making a generator):
* take in necessary data as input
* run matrix multiplication for matching
* do necessary indexing
* yield match information

**Comment by nOkuda** [comment]
If speed is the only thing that needs fixing, I think it would be good to merge this pull request in.  We can address the speed issue in a new pull request.

**Comment by jeffkinnison** [comment]
A couple of questions:
1) Why are we folding Match Entities into their MatchSet? I find it hard to believe that looking up Matches with find() filtered by MatchSet id is a huge bottleneck, at least no more so than looking up the Matches by id.
2) To prevent bloat, do we possibly want to make ResultsStatus a field in MatchSet rather than its own entity? What's the benefit of having it separate? If the reason for separation is an instantiation problem, I'm fine with intantiating & committing MatchSet somewhere other than at the end of search().
3) Are MatchResult entities added to the database? That seems like something we could consolidate into Match entities.

I still have to spool through all of the retrieval code, and my machine isn't cooperating with checking out branches from your fork for some reason.

**Comment by nOkuda** [comment]
Thanks for your thoughts.  Hopefully, I can explain my decisions effectively enough to induce a productive discussion.
1.  My recollection, as surprising as you may find it, is that find() on Matches filtered by MatchSet id was the bottleneck (the big jump from minutes to seconds).  The change probably happened at commit 5efab91, if you wanted to verify it yourself.  Certainly, MongoDB automatically indexes by _id, so searching Matches by _id instead of by MatchSet id will be faster by some amount.  But it's also possible that that commit introduced an optimization for querying the database fewer times.  Even so, I suspect that as the number of Matches in the database grows, searching by _id will become more important for speed reasons.  So I'm inclined to keep Match _id's in MatchSets.
2.  I think consolidation is possible.  I think that I had originally separated ResultsStatus from MatchSet to make the search status accessible to the API.  But I end up updating ResultStatus during the search run, so it wouldn't be crazy to update MatchSet instead.  We'd just need to generate the MatchSet prior to executing search and then fill in the Match data after the search completes.  This could also simplify the API in that instead of generating a UUID to associate with the MatchSet, it could just look up by the MatchSet _id directly.  The only concern there would be a matter of object purity:  the MatchSet defines only the Matches belonging to a search parameter setting.  On the other hand, those search parameters are stuffed in there, so what more could it hurt to stuff search status information into the already overstuffed MatchSet?  Not sure.  I suppose as far as the search cache goes, it would make even more sense to have the ResultsStatus hold the search parameters along with the status information and make the MatchSet exist only when the search completes successfully.  That might make the object purity better:  MatchSet deals with v5 internals, ResultsStatus handles API related things.  Ah!  So the search results cache behavior relies on the fact that the MatchSet gets committed with search parameters only when the search completes successfully.  It wouldn't be too hard to make the extra check for cache lookup whether the consolidated MatchSet successfully completed.  If after those musings, you're still rooting for consolidation, I'd be willing to try it.
3.  I believe that MatchResults were changed to ResultsStatuses.  So MatchResults aren't committed to the database, but ResultsStatuses are.

On the matter of your git woes, I have some thoughts.  If it's a merge conflict issue, then rewind to 6 commits previous on your fork's master, checkout a branch at that commit, and then try merging from that new branch (your fork on github reports:  "This branch is 6 commits ahead, 11 commits behind tesserae:master.")  If it's a remote branch configuration issue, here's the part of my .git/config that pertains to how I got updates from your fork:
```
[remote "bleeding"]
	url = git@github.com:jeffkinnison/tesserae-v5.git
	fetch = +refs/heads/*:refs/remotes/bleeding/*
```
I think I was able to configure all of that via `git remote`, but I can't remember the details anymore.

**Comment by jeffkinnison** [comment]
Maybe the solution to 1) would be to optimize the matches collection in Mongo for searches by MatchSet id. We should be able to automate that setup in some way inside of Tesserae, maybe running it as a post-install step or an automatic step when a TessMongoConnection is created. This is more of a "principle of least surprise" thing for me than anything else: if I have some database entry with a one-to-many relationship to some other entities, I would expect the singleton to be my point of entry for lookups or joins. I'll play around with that optimization this week and see if it gives us a speedup.

For 2), maybe the nicer way of handling it would be to discard MatchSet and ResultsStatus in favor of one entity called Search that encompasses data related to the entire search process for one set of parameters including asynchronous updates. From a process standpoint, this makes sense to me because it conceptually wraps around the single user-facing action of a search and limits the cognitive overhead of managing a bunch of different entities for users of the API.

On the remote issue--I'm not sure what the problem is since I'm connected to your fork in config and should be able to checkout without merging. Will get back to you when that's resolved.

**Comment by nOkuda** [comment]
On 1), if we can figure out how to make the mongodb indexing maintenance run automatically and never fail and never interfere, that sounds fine.  I just want to avoid pain and frustration for the Tesserae fellow seven years down the road when the cron job fails or something like that.

I'll do consolidation per 2) once I've coded up the speed up to search I had envisioned (before I forget the details on how I got it to work; I have a sinking suspicion that it's still going to be slow, though, based on algorithmic complexity).

**Comment by nOkuda** [comment]
It has finally occurred to me what you meant by MatchResult.  Sorry for my earlier confusion.  Yes, you are right---Match could be updated to contain the information in MatchResult.  I had originally created MatchResult as an interface between the API and Match, but I like the idea of making Match conform to MatchResult.  I'll be working on that next, so if you don't get to merging this pull request before I finish that work, I'll add it to this pull request.  Otherwise, I'll open a new pull request with that work.

**Comment by jeffkinnison** [comment]
This looks good and aligns with v3 search results. Let's go ahead and merge this, then we can work on making it faster.

**Pull request merged**
